use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum UsageCategory {
    ModelText,
    ModelReasoning,
    Embedding,
    Reranker,
    AudioTts,
    AudioSt,
    ImageGeneration,
    VideoGeneration,
    MusicGeneration,
    ToolExecution,
    ChannelDelivery,
    ArtifactStorage,
    NodeExecution,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UsageRecord {
    pub usage_id: String,
    pub category: UsageCategory,
    pub provider_id: Option<String>,
    pub model_id: Option<String>,
    pub resource_id: String,
    pub endpoint_id: Option<String>,
    pub region: Option<String>,
    pub account_id: Option<String>,
    pub project_id: Option<String>,
    pub workspace_id: Option<String>,
    pub agent_id: Option<String>,
    pub session_id: Option<String>,
    pub task_id: Option<String>,
    pub plugin_id: Option<String>,
    pub request_count: u32,
    pub response_count: u32,
    pub message_count: u32,
    pub input_tokens: Option<u64>,
    pub output_tokens: Option<u64>,
    pub cached_tokens: Option<u64>,
    pub reasoning_tokens: Option<u64>,
    pub audio_seconds: Option<f64>,
    pub image_count: Option<u32>,
    pub video_count: Option<u32>,
    pub tool_call_count: Option<u32>,
    pub context_window_used: Option<u64>,
    pub max_context_tier_crossed: Option<String>,
    pub started_at: chrono::DateTime<chrono::Utc>,
    pub ended_at: chrono::DateTime<chrono::Utc>,
    pub latency_ms: u64,
    pub retry_count: u32,
}
